spring:
  application:
    name: e-commerce
  server:
    port: 8081
  datasource:
    url: ${POSTGRES_HOST}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

admin:
  email: ${ADMIN_EMAIL}
  password: ${ADMIN_PASSWORD}
  name: ${ADMIN_NAME}
  cpf: ${ADMIN_CPF}
  phone: ${ADMIN_PHONE}

stripe:
  secret-key: ${STRIPE_SECRET_KEY}
